### ISSUE TITLE
closing of client

### ISSUE THREAD

**Issue by cdaringe** [hapijs/good-udp#32]
hello:

you mention that you don't close the client.  is there a reason for this?  it seems like a little teardown method could simply proxy dgram::close()?

just curious!

thanks

**Comment by vdeturckheim** [comment]
The choice had been made to have it that way.

Do you need a closing method to be implemented ? Actually with the upgrade to the Stream interface I think it should be possible to call `.end()` on the stream.

**Comment by arb** [comment]
You could add a listener in the constructor for the "end" event I believe.

**Comment by vdeturckheim** [comment]
@arb :+1: good idea !
